name: artnet-hue-entertainment-multiple

x-artnet-hue-common: &artnet-hue-common
  image: ghcr.io/einlichtvogel/artnet-hue-entertainment:latest
  pull_policy: always
  init: true
  network_mode: host
  restart: unless-stopped
  user: "${ARTNET_HUE_UID:-1000}:${ARTNET_HUE_GID:-1000}"
  command: ["run", "--config", "/data/config.json"]

services:
  bridge-main:
    <<: *artnet-hue-common
    volumes:
      - ./data/main:/data

  bridge-stage:
    <<: *artnet-hue-common
    volumes:
      - ./data/stage:/data
